name: rss_to_subreddit
services:
  rss_to_subreddit:
    container_name: rss-script
    image: rss-to-subreddit
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    stdin_open: true
    tty: true
    environment:
      - TZ=
    #  - DISCORD_WEBHOOK_URL=
    volumes:
      - ./db:/app/db
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 100M
        reservations:
          cpus: '0.10'
          memory: 20M
